=== tericcabrel/throner-api/doc/schemas/users/get-responses-200.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "http://localhost/api-doc/schemas/",
    "type": "array",
    "description": "The list of users.",
    "items": {
      "type": "object",
      "properties": {
         "user_id" : {
          "type": "string",
          "description": "User id"
        },
         "name": {
          "type": "string",
          "description": "User name"
        },
        "username" : {
          "type": "string",
          "description": "User name"
        },
         "email" : {
          "type": "string",
          "description": "User email address",
          "format": "email"
        }
      },
     "required": [ "user_id","name", "username", "email"]
    }
    
}

=== tericcabrel/throner-api/doc/examples/users/get-responses-200.json
[
    {
      "user_id": "9llee3d0e-dd36-4a44-b71a-70lkh7c7f077",
      "email": "ulrich@example.com",
      "name" : "ulrich",
      "username" : "ntella"
    },
    {
      "user_id": "99ee3d0e-dd36-4a44-b71a-70b8b7c7f077",
      "email": "rodrique@example.com",
      "name" : "Rodrigue",
      "username" : "Taje"
    }
]
